/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART_1.h"
#include "Clock_1.h"
#include "QuadDec_Motor.h"
#include "Pin_B_S2_aliases.h"
#include "Pin_B_S2.h"
#include "Pin_A_S2_aliases.h"
#include "Pin_A_S2.h"
#include "QuadDec_Sensor.h"
#include "Pin_A_S1_aliases.h"
#include "Pin_A_S1.h"
#include "Pin_B_S1_aliases.h"
#include "Pin_B_S1.h"
#include "Clock_2.h"
#include "Pin_1_aliases.h"
#include "Pin_1.h"
#include "ADC_DelSig_1.h"
#include "Pin_2_aliases.h"
#include "Pin_2.h"
#include "timer_clock.h"
#include "Timer.h"
#include "isr_Timer.h"
#include "PWM.h"
#include "H_Enable_aliases.h"
#include "H_Enable.h"
#include "H_Dir2_aliases.h"
#include "H_Dir2.h"
#include "H_Dir1_aliases.h"
#include "H_Dir1.h"
#include "UART_1_IntClock.h"
#include "QuadDec_Motor_Cnt16.h"
#include "QuadDec_Sensor_Cnt16.h"
#include "ADC_DelSig_1_AMux.h"
#include "ADC_DelSig_1_Ext_CP_Clk.h"
#include "ADC_DelSig_1_IRQ.h"
#include "ADC_DelSig_1_theACLK.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

